version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: sats-btcpay-altcoins_web_1
      APP_PORT: 49392
      PROXY_AUTH_ADD: "false"
  web:
    image: btcpayserver/btcpayserver:1.8.1-altcoins@sha256:2ee57e0ba118406c286d7a9fd70f684bdbfd0a1a8e5b890aeb2e81e915a3ea72 # 1.8.1-altcoins
    user: "root:root"
    restart: on-failure
    stop_grace_period: 1m
    container_name: sats-btcpay-altcoins_web_1
    expose:
      - "49392"
    depends_on: [nbxplorer, postgres]
    entrypoint: ["dotnet", "BTCPayServer.dll"]
    volumes:
      - ${APP_DATA_DIR}/data/btcpay:/data
      - ${APP_DATA_DIR}/data/nbxplorer:/data/.nbxplorer
      - ${APP_DATA_DIR}/data/btcpay_pluginsdir:/data/plugins
      - ${APP_LIGHTNING_NODE_DATA_DIR}:/lnd:ro
      - ${APP_DATA_DIR}/data/xmr_wallet:/root/xmr_wallet
    environment:
      HOME: "/data"
      BTCPAY_DATADIR: "/data"
      BTCPAY_PLUGINDIR: "/data/plugins"
      BTCPAY_DOCKERDEPLOYMENT: "false"
      BTCPAY_POSTGRES: "User ID=postgres;Host=sats-btcpay-altcoins_postgres_1;Port=5432;Database=btcpayserver$APP_BITCOIN_NETWORK"
      BTCPAY_NETWORK: "$APP_BITCOIN_NETWORK"
      BTCPAY_BIND: 0.0.0.0:49392
      BTCPAY_CHAINS: "btc,xmr"
      BTCPAY_BTCEXPLORERURL: "http://sats-btcpay-altcoins_nbxplorer_1:32838"
      BTCPAY_XMR_DAEMON_URI: http://sats-btcpay-altcoins_monerod_1:18081
      BTCPAY_XMR_WALLET_DAEMON_URI: http://sats-btcpay-altcoins_monerod_wallet_1:18082
      BTCPAY_XMR_WALLET_DAEMON_WALLETDIR: /root/xmr_wallet
      BTCPAY_BTCLIGHTNING: "type=lnd-rest;server=https://$APP_LIGHTNING_NODE_IP:$APP_LIGHTNING_NODE_REST_PORT/;macaroonfilepath=/lnd/data/chain/bitcoin/$APP_BITCOIN_NETWORK/admin.macaroon;allowinsecure=true"
      BTCPAY_SOCKSENDPOINT: $TOR_PROXY_IP:$TOR_PROXY_PORT
      BTCPAY_EXPLORERPOSTGRES: User ID=postgres;Host=sats-btcpay-altcoins_postgres_1;Port=5432;Application Name=nbxplorer;MaxPoolSize=20;Database=nbxplorer$APP_BITCOIN_NETWORK
      BTCPAY_TORSERVICES: "sats-btcpay-altcoins_web_1:$APP_HIDDEN_SERVICE"

  nbxplorer:
    image: nicolasdorier/nbxplorer:2.3.62@sha256:8f484e37fc2ab7f9bf7524ad7d4d5a09a39d5bc3dee5f84cfa43f93be3396e92
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    depends_on: [postgres]
    container_name: sats-btcpay-altcoins_nbxplorer_1
    expose:
      - "32838"
    volumes:
      - ${APP_DATA_DIR}/data/nbxplorer:/data
    environment:
      NBXPLORER_DATADIR: "/data"
      NBXPLORER_NETWORK: "$APP_BITCOIN_NETWORK"
      NBXPLORER_BIND: 0.0.0.0:32838
      NBXPLORER_CHAINS: "btc"
      NBXPLORER_SIGNALFILEDIR: "/data"
      NBXPLORER_BTCRPCURL: "http://$APP_BITCOIN_NODE_IP:$APP_BITCOIN_RPC_PORT"
      NBXPLORER_BTCNODEENDPOINT: $APP_BITCOIN_NODE_IP:$APP_BITCOIN_P2P_PORT
      NBXPLORER_BTCRPCUSER: $APP_BITCOIN_RPC_USER
      NBXPLORER_BTCRPCPASSWORD: $APP_BITCOIN_RPC_PASS
      NBXPLORER_POSTGRES: User ID=postgres;Host=sats-btcpay-altcoins_postgres_1;Port=5432;Application Name=nbxplorer;MaxPoolSize=20;Database=nbxplorer$APP_BITCOIN_NETWORK
      NBXPLORER_AUTOMIGRATE: 1
      NBXPLORER_NOMIGRATEEVTS: 1
      NBXPLORER_BTCHASTXINDEX: 1

  monerod:
    restart: unless-stopped
    container_name: sats-btcpay-altcoins_monerod_1
    stop_grace_period: 1m
    user: "root:root"
    image: btcpayserver/monero:0.18.1.1
    entrypoint: monerod --rpc-bind-ip=0.0.0.0 --confirm-external-bind --rpc-bind-port=18081 --non-interactive --block-notify="/bin/sh ./scripts/notifier.sh -X GET http://sats-btcpay-altcoins_web_1:49392/monerolikedaemoncallback/block?cryptoCode=xmr&hash=%s" --hide-my-port --prune-blockchain --enable-dns-blocklist
    expose:
      - "18080"
      - "18081"
    volumes:
      - ${APP_DATA_DIR}/data/xmr_data:/home/monero/.bitmonero
      - ${APP_DATA_DIR}/data/xmr_wallet:/wallet


  monerod_wallet:
    restart: unless-stopped
    container_name: sats-btcpayserver_monero_wallet_1
    stop_grace_period: 1m
    image: btcpayserver/monero:0.18.1.1
    entrypoint: monero-wallet-rpc --rpc-bind-ip=0.0.0.0 --disable-rpc-login --confirm-external-bind --rpc-bind-port=18082 --non-interactive --trusted-daemon  --daemon-address=monerod:18081 --wallet-file=/wallet/wallet --password-file=/wallet/password --tx-notify="/bin/sh ./scripts/notifier.sh  -X GET http://web:49392/monerolikedaemoncallback/tx?cryptoCode=xmr&hash=%s"
    expose:
      - "18082"
    volumes:
      - ${APP_DATA_DIR}/data/xmr_data:/home/monero/.bitmonero
      - ${APP_DATA_DIR}/data/xmr_wallet:/wallet
    depends_on:
      - monerod

  postgres:
    image: btcpayserver/postgres:13.7@sha256:dadf0048895a888d88a2dd773dde2f5868c45f74ad37c6d208694df54b590531
    # This needs to run as root for migrations to succeed
    # user: "1000:1000"
    container_name: sats-btcpay-altcoins_postgres_1
    restart: on-failure
    # https://github.com/btcpayserver/btcpayserver-docker/commit/a65e7db6851092c75c5ac6c091a5f36ccc5fc26e
    command: ["-c", "random_page_cost=1.0", "-c", "shared_preload_libraries=pg_stat_statements"]
    stop_grace_period: 1m
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ${APP_DATA_DIR}/data/postgres:/var/lib/postgresql/data